---

- name: Configure apt to use HTTP proxy
  template: src=apt.conf.j2 dest=/etc/apt/apt.conf
  when: ansible_os_family == "Debian"

- name: Configure yum to use HTTP proxy
  lineinfile: dest=/etc/yum.conf line="proxy={{ http_proxy }}"
  when: ansible_os_family == "RedHat"
