---
# master vars
master_name: HANA_BDH
master_image: ami-7215851d  #suse 12.3
master_instance_type: t2.2xlarge
#master_instance_type: t2.small

# worker vars
number_of_workers: 0
worker_name_prefix: HADOOP_BDH_
worker_image: ami-194cdc76
worker_instance_type: t2.xlarge

aws_key_name: ansible
aws_region: eu-central-1
ec2_endpoint_url: https://ec2.eu-central-1.amazonaws.com

aws_security_group_id: sg-a0d036cd   #vpc-1aa10771;created for hana
aws_vpc_subnet_id: subnet-8f264de4   #vpc-1aa10771;created for hana;10.249.1.0/24

aws_ssh_user: ec2-user #for centos, the user is centos, others is ec2-user or root

aws_volume_size: 200
aws_cluster_zone: eu-central-1a
aws_device_type: gp2
device_name: /dev/sda1

#https://aws.amazon.com/ec2/pricing/on-demand/
supported_instance_type:
  - t2.small    #1/2   VPUs/Memory(G)
  - t2.medium   #2/4   VPUs/Memory(G)
  - t2.xlarge   #4/16  VPUs/Memory(G)
  - t2.2xlarge  #8/32  VPUs/Memory(G)
  - m5.4xlarge  #16/64 VPUs/Memory(G)

supported_aws_images_eu_central_1:
  - ami-1b2bb774 #amazon linux 2
  - ami-7215851d #suse 12.3
  - ami-2b3cac44 #suse 11.4
  - ami-194cdc76 #redhat 7.4
  - ami-5055cd3f #ubuntu 16.04
  - ami-fa2fb595 #ubuntu 14.04

supported_aws_images_eu_west_1:
  - ami-0d063c6b #centos 7 1703_01 for eu-west-1

supported_aws_images_eu_east_1:
  - ami-428aa838 #amazon linux

supported_aws_zones:
  - eu-central-1a
  - eu-west-1a
  - eu-east-1a
