
- name: set extra parameters
  set_fact:
    slp_extra_parameters: "-e hana.resources.requests.memory={{ hana_resources_requests_memory }} \
                           -e hana.resources.limits.memory={{ hana_resources_limits_memory }} \
                           -e vora-vsystem.policy.cacheValidity=5ms \
                           -e hana.resources.requests.cpu=0.5 \
                           -e uaa.cpu.min=0.25"
  tags:
    - uninstall

- name: set args for one node installation
  set_fact:
    slp_extra_parameters: "{{ slp_extra_parameters }} \
                           -e=vora-cluster.components.dlog.replicationFactor=1 \
                           -e=vora-cluster.components.dlog.standbyFactor=0"
  when: bdh_one_node_installation == "yes"
  tags:
    - uninstall
  no_log: true

- name: set args for one node and hanalite-dqp-test in push validation
  set_fact:
    slp_extra_parameters: "{{ slp_extra_parameters }} \
                           -e=vora-cluster.components.catalog.resources.limits.memory=\"\" -e=vora-cluster.components.catalog.resources.requests.memory=\"\" \
                           -e=vora-cluster.components.landscape.resources.limits.memory=\"\" -e=vora-cluster.components.landscape.resources.requests.memory=\"\" \
                           -e=vora-cluster.components.dlog.resources.limits.memory=\"\" -e=vora-cluster.components.dlog.resources.requests.memory=\"\" \
                           -e=vora-cluster.components.disk.resources.limits.memory=\"\" -e=vora-cluster.components.disk.resources.requests.memory=\"\" \
                           -e=vora-cluster.components.relational.resources.limits.memory=\"\" -e=vora-cluster.components.relational.resources.requests.memory=\"\" \
                           -e=vora-cluster.components.txBroker.resources.limits.memory=\"\" -e=vora-cluster.components.txBroker.resources.requests.memory=\"\" \
                           -e=vora-cluster.components.txLockManager.resources.limits.memory=\"\" -e=vora-cluster.components.txLockManager.resources.requests.memory=\"\" \
                           -e=vora-cluster.components.txCoordinator.resources.limits.memory=\"\" -e=vora-cluster.components.txCoordinator.resources.requests.memory=\"\" "
  when: bdh_one_node_installation == "yes"
  tags:
    - uninstall

- name: judge dev config file is exits or not
  shell: ls {{ dev_config_file }}
  ignore_errors: True
  register: dev_config_file_result
  when: dev_config_file is defined
  tags:
    - uninstall

- name: set dev config file
  set_fact:
    slp_extra_parameters: "{{ slp_extra_parameters }} --dev-config-file={{ dev_config_file }}"
  when: dev_config_file is defined and dev_config_file_result.rc == 0
  tags:
    - uninstall
  no_log: true


- name: set_fact slcb_init = true
  set_fact:
    slcb_init: "true"
  tags:
    - uninstall
- name: generate inifile for slcb init
  include: generate-inifile.yml
  tags:
    - uninstall

- name: Set SAP Docker private repository
  set_fact:
    docker_repository_flag: "--SAP_PV_DOCKER_REPO {{ docker_artifactory }}"
  tags:
  - uninstall

- name: Set SAP Docker repository to use default
  set_fact:
    docker_repository_flag: ""
  when: docker_artifactory is undefined or docker_artifactory == ""
  tags:
  - uninstall

- name: Set product bridge flag 
  set_fact:
    product_bridge_flag: "--useBridgeImage {{ product_bridge_name }}:{{ vorapkg_version }}"
  tags:
  - uninstall

- name: Set eks repository suffix as default
  set_fact:
    eks_repository_suffix: ""
  when: eks_docker_registry_suffix is undefined or eks_docker_registry_suffix == ""
  tags:
  - uninstall

- name: Set eks repository suffix as default
  set_fact:
    eks_repository_suffix: "{{ eks_docker_registry_suffix }}/"
  when: eks_docker_registry_suffix is defined and eks_docker_registry_suffix != ""
  tags:
  - uninstall

- name: download slcb
  include: download-slcb.yml
  tags:
  - uninstall

- name: create missing repositories product-bridge in default
  shell: "aws ecr create-repository --repository-name={{ eks_repository_suffix }}{{ product_bridge_name }}"
  environment:
    "{{ installer_env }}"
  args:
    executable: /bin/bash
  ignore_errors: true
  tags:
    - uninstall

- name: create missing repositories in bridge
  shell: "{{role_path}}/files/aws_create_repositories_slcb.sh {{ installer_workspace }} {{ docker_artifactory }} {{ product_bridge_name }}:{{ vorapkg_version }}"
  environment:
    "{{ installer_env }}"
  args:
    chdir: "{{role_path}}/files"
    executable: /bin/bash
  ignore_errors: true
  when: eks_docker_registry_suffix is undefined or eks_docker_registry_suffix == ""
  tags:
    - uninstall

- name: create missing repositories in bridge with suffix
  shell: "{{role_path}}/files/aws_create_repositories_slcb.sh {{ installer_workspace }} {{ docker_artifactory }} {{ product_bridge_name }} {{ vorapkg_version }} {{ eks_docker_registry_suffix }}"
  environment:
    "{{ installer_env }}"
  args:
    chdir: "{{role_path}}/files"
    executable: /bin/bash
  ignore_errors: true
  when: eks_docker_registry_suffix is defined and eks_docker_registry_suffix != ""
  tags:
    - uninstall

- name: create missing repositories in bridge with vflow registry
  shell: "{{role_path}}/files/aws_create_repositories_slcb.sh  {{ installer_workspace }} {{ docker_artifactory }} {{ product_bridge_name }}:{{ vorapkg_version }} {{ eks_vflow_docker_registry_suffix }}"
  environment:
    "{{ installer_env }}"
  args:
    chdir: "{{role_path}}/files"
    executable: /bin/bash
  ignore_errors: true
  when: eks_vflow_docker_registry_suffix is defined and eks_vflow_docker_registry_suffix != ""
  tags:
    - uninstall

- name: workaround step for SLCB 1.1.44+
  shell: "./slcb copy {{ docker_repository_flag }} -i {{ installer_workspace }}/inifile {{ product_bridge_flag }} -u none 2>&1 | tee slcb_copy_workaround.log; exit ${PIPESTATUS[0]}"
  environment:
    "{{ installer_env }}"
  args:
    chdir: "{{ installer_workspace }}"
    executable: /bin/bash
  register: slcb_copy_workaround_result
  until: slcb_copy_workaround_result.rc == 0
  retries: 3
  delay: 60
  tags:
    - uninstall

- name: slcb init
  # workaround for SLCB 1.1.44
  #shell: "./slcb init -i {{ installer_workspace }}/inifile --namespace {{ slc_ns }} {{ docker_repository_flag }} -u none 2>&1 | tee slcb_init_process.log; exit ${PIPESTATUS[0]}"
  shell: "./slcb init -i {{ installer_workspace }}/inifile --namespace {{ slc_ns }} -u none 2>&1 | tee slcb_init_process.log; exit ${PIPESTATUS[0]}"
  environment:
    "{{ installer_env }}"
  args:
    chdir: "{{ installer_workspace }}"
    executable: /bin/bash
  ignore_errors: true
  register: installation_result_via_slcb
  until: installation_result_via_slcb.rc == 0
  retries: 3 # workaround the first slcb init failure
  delay: 5
  tags:
    - uninstall

- name: dump slcb.log
  shell: "cat {{ installer_workspace }}/slcb.log"
  environment:
    "{{ installer_env }}"
  args:
    chdir: "{{ installer_workspace }}"
    executable: /bin/bash
  tags:
    - uninstall

- name: Fail if init failed
  assert: { that: "installation_result_via_slcb.rc == 0 and installation_result_via_slcb.changed == true" }
  tags:
    - uninstall

- name: slcb mirror
  shell: "./slcb copy -l debug -i inifile {{ docker_repository_flag }} {{ product_bridge_flag }} -u none 2>&1 | tee slcb_copy_process.log; exit ${PIPESTATUS[0]}"
  environment:
    "{{ installer_env }}"
  args:
    chdir: "{{ installer_workspace }}"
    executable: /bin/bash
  register: slcb_copy_result
  until: slcb_copy_result.rc == 0
  retries: 3
  delay: 60
  tags:
    - uninstall

- name: set_fact slcb_init = false
  set_fact:
    slcb_init: "false"
  tags:
    - uninstall

- name: generate inifile for slcb execute
  include: generate-inifile.yml
  tags:
    - uninstall

- name: uninstall the vora via slcb
  shell: "./slcb execute -i inifile --namespace {{ slc_ns }} {{ docker_repository_flag }} {{ product_bridge_flag }} -u none 2>&1 | tee slcb_execute_process.log; exit ${PIPESTATUS[0]}"
  environment:
    "{{ installer_env }}"
  args:
    chdir: "{{ installer_workspace }}"
    executable: /bin/bash
  ignore_errors: true
  register: installation_result_via_slcb
  tags:
    - uninstall

- block:
  - name: Create pods logs directory
    file: path="{{ installer_workspace }}/logs/podlogs" state=directory
  - name: Collect current logs
    shell: "python {{role_path}}/files/log_collector.py {{ installer_workspace }}/logs/podlogs --namespace {{ vora_kube_namespace }}"
    environment:
      "{{ installer_env }}"
  ignore_errors: true
  tags:
    - uninstall

- block:
  - name: Create pods describe logs directory
    file:
      path: "{{ installer_workspace }}/logs/pod_des_logs"
      state: directory
  - name: save all pod describe log
    shell: "python {{role_path}}/../vora-kubernetes-install/files/generate_pods_describe_log.py {{ vora_kube_namespace }} {{ installer_workspace }}/logs/pod_des_logs"
    environment:
        "{{ installer_env }}"
  ignore_errors: true
  tags:
    - uninstall

- name: copy slcb log files to playbook folder
  shell: "cp {{ installer_workspace }}/slcb*.log ./"
  args:
    executable: /bin/bash
  ignore_errors: true
  tags:
    - uninstall

- name: archive the slcb logs folder
  archive:
    path: "{{ installer_workspace }}/slcb.log"
    dest: "{{ installer_workspace }}/{{ slcb_log }}"
    format: zip
  ignore_errors: true
  tags:
    - uninstall

- name: copy slcb log zip to playbook folder
  fetch:
    src: "{{ installer_workspace }}/{{ slcb_log }}"
    dest: "{{ slcb_log }}"
    flat: yes
  ignore_errors: true
  tags:
    - uninstall

- name: archive the logs folder
  archive:
    path: "{{ installer_workspace }}/logs"
    dest: "{{ installer_workspace }}/{{ archive_logs }}"
    format: zip
  ignore_errors: true
  tags:
    - uninstall
    
- name: copy logs to playbook folder
  fetch:
    src: "{{ installer_workspace }}/{{ archive_logs }}"
    dest: "{{ archive_logs }}"
    flat: yes
  ignore_errors: true
  tags:
    - uninstall

- name: Fail if installation via slcb failed
  assert: { that: "installation_result_via_slcb.rc == 0 and installation_result_via_slcb.changed == true" }
  tags:
    - uninstall
