---
- name: Set default install flag
  set_fact:
    install_flag: "uninstall"
  tags:
    - uninstall

- name: set installer env
  set_fact:
    installer_env:
      KUBECONFIG: "{{gke_k8s_cluster_kubeconfig}}"
  tags:
    - uninstall

- name: Starting vora uninstallation process via slcb
  include: gke-uninstall-vora-slcb.yml
  when: uninstall_via_slcb == "true"

