---
- include_role:
    name: vora-kubernetes-install-cloud
    tasks_from: eks-docker-login.yml
  tags:
    - uninstall

- name: get recordset from route53
  route53:
    command: get
    zone: "{{ eks_dns_zone }}"
    record: "{{ eks_k8s_cluster_name | replace('_', '-') }}-eks.infra.{{ eks_dns_zone }}"
    type: CNAME
  register: result_recordset_ingress
  ignore_errors: yes

- debug:
    var: result_recordset_ingress

- name: delete recordset
  route53:
    command: delete
    zone: "{{ eks_dns_zone }}"
    record: "{{ result_recordset_ingress.set.record }}"
    ttl: "{{ result_recordset_ingress.set.ttl }}"
    type: "{{ result_recordset_ingress.set.type }}"
    value: "{{ result_recordset_ingress.set.value }}"
  when: result_recordset_ingress.set.record is defined

- name: Set Vora uninstall command
  set_fact:
    installer_env:
      KUBECONFIG: "{{ eks_k8s_cluster_kubeconfig }}"
    installer_base_cmd: "--purge \
                         --force-deletion \
                         --namespace={{ vora_kube_namespace }} \
                         --docker-registry={{ eks_docker_registry }} \
                         --deployment-type=cloud \
                         --disable-installer-logging"
  tags:
    - uninstall

