---
- name: ref the gcloud common vars
  include_vars:
    file: "{{ role_path }}/../gcloud-vars.yml"

- name: initialize worker_instances variable
  set_fact:
    worker_instances: []

- name: Set google cloud Service Account environment
  set_fact:
    gcloud_service_account_credentials: "{{ lookup('file',google_application_credentials) | from_json }}"

- name: set fact for instance ssh public key
  set_fact:
    ssh_pubkey: "{{ lookup('file', 'id_rsa.pub') }}"
