gcloud_project_id: "sap-p-and-i-big-data-vora"
# The gcloud region and zone neet matched for use , see detail at: https://cloud.google.com/compute/docs/regions-zones/
gcloud_region: "us-central1"
gcloud_zone: "us-central1-a"
gcloud_ssh_user: "ansible"

gcloud_image_family: "sles-12"
gcloud_instance_name: "bdh-infra-instance"
gcloud_instance_master_name: "{{ gcloud_instance_name }}-master"
gcloud_instance_worker_name_prefix: "{{ gcloud_instance_name }}-worker-"
gcloud_number_of_workers: 0
gcloud_instance_machine_type: "n1-standard-8"
gcloud_instance_image_type: "sles-12-sp3-v20180104"
gcloud_instance_master_external_ip: "{{ gcloud_instance_master_name }}-external-ip"
gcloud_instance_disk_size: 100
gcloud_instance_sa_permissions:
  - storage-full
  - compute-rw
  - service-management
gcloud_instance_tags:
  - http-server
  - https-server

k8s_version: "1.8.8-gke.0"
number_of_workers: 3
gcloud_k8s_cluster_node_machine_type: "n1-standard-4"
gcloud_k8s_cluster_node_image_type: "cos"
gcloud_k8s_cluster_node_disk_size: 100
gcloud_persistent_disk_size: 20
gcloud_k8s_vpc: "im-vpc"
gcloud_k8s_subnetwork: "data-hub-im-web"
