---
- name: judge dev config file is exits or not
  shell: ls {{ dev_config_file }}
  ignore_errors: yes
  register: dev_config_file_result
  when: dev_config_file is defined
  tags:
    - install
    - update

- name: set dev config file
  set_fact:
    extra_install_parameters: "{{ extra_install_parameters }} --dev-config-file={{ dev_config_file }}"
  when: dev_config_file is defined and dev_config_file_result.rc == 0
  tags:
    - install
    - update
  no_log: true

# resume block
- block:
  - name: Get backup bucket
    shell: echo {{ di_backup_name }} | awk -F '/' '{print $1"/"$2"/"$3}'
    register: backup_bucket

  - name: Get backup name
    shell: echo {{ di_backup_name }} | awk -F '/' '{print $4}'
    register: backup_name

  - name: Get backup timestamp
    shell: echo {{ di_backup_name }} | awk -F '/' '{print $5}'
    register: backup_timestamp
      
  - name: Get backup date
    shell: date -d "@{{ backup_timestamp.stdout }}" +"%Y-%m-%d %H:%M:%S %:z"
    register: backup_date

  when: enable_restore is defined and enable_restore == "true"
  environment:
    KUBECONFIG: "{{ azure_kubeconfig }}"
  tags:
    - install

- name: set_fact slcb_init = true
  set_fact:
    slcb_init: "true"
  tags:
    - install
    - update

- name: generate inifile for slcb init
  include: generate-inifile.yml
  tags:
    - install
    - update

- name: Set SAP Docker repository to use default
  set_fact:
    docker_repository_flag: ""
  when: docker_artifactory is undefined or docker_artifactory == ""
  tags:
    - install
    - update

- name: Set SAP Docker private repository
  set_fact:
    docker_repository_flag: "--SAP_PV_DOCKER_REPO {{ docker_artifactory }}"
  tags:
    - install
    - update

- name: Set product bridge flag
  set_fact:
    product_bridge_flag: "--useBridgeImage {{ product_bridge_name }}:{{ vorapkg_version }}"
  tags:
    - install
    - update

- name: download slcb
  include: download-slcb.yml
  tags:
    - install
    - update

- name: add placeholder at vara_installation.log file
  shell: "echo 'DI installed via slcb, please see details info at slcb log...' >> {{ vora_installation_log }}"
  ignore_errors: yes

- name: docker login before installation
  shell: docker login -u {{ azure_docker_login_username }} -p {{ azure_docker_login_password }} https://{{ azure_docker_login_address }}
  register: docker_login_result
  until: docker_login_result.rc == 0
  retries: 3
  delay: 180
  tags:
    - install
    - update

# - name: docker login before installation for vflow registry
#   shell: docker login -u {{client_id}} -p {{client_secret}} https://{{ azure_vflow_registry_name }}.azurecr.io
#   register: docker_login_result
#   until: docker_login_result.rc == 0
#   retries: 3
#   delay: 180
#   when: azure_vflow_registry_name is defined and azure_vflow_resource_group is defined
#   tags:
#     - install
#     - update

- name: set up refresh token cron job each 1 hour
  cron:
    name: "refresh acr token"
    special_time: "hourly"
    job: "docker login -u {{azure_docker_login_username}} -p {{azure_docker_login_password}} https://{{ aks_docker_install_registry }}"
  when: azure_vflow_registry_name is not defined
  tags:
    - install
    - update

- name: docker login before installation for vflow registry
  cron:
    name: "refresh acr token"
    special_time: "hourly"
    job: "docker login -u {{azure_docker_login_username}} -p {{azure_docker_login_password}} https://{{ aks_docker_install_registry }}"
  when: azure_vflow_registry_name is defined and azure_vflow_resource_group is defined
  tags:
    - install
    - update

- name: workaround step for SLCB 1.1.44+
  shell: "./slcb copy {{ docker_repository_flag }} -i {{ installer_workspace }}/inifile {{ product_bridge_flag }} -u none 2>&1 | tee slcb_copy_workaround.log; exit ${PIPESTATUS[0]}"
  environment:
    "{{ installer_env }}"
  args:
    chdir: "{{ installer_workspace }}"
    executable: /bin/bash
  ignore_errors: yes
  register: slcb_copy_workaround_result
  until: slcb_copy_workaround_result.rc == 0
  retries: 3
  delay: 60
  tags:
    - install
    - update
- block:
  - name: slcb init
    # workaround for SLCB 1.1.44
    #shell: "./slcb init -l debug -i inifile --namespace {{ slc_ns }} {{ docker_repository_flag }} -u none 2>&1 | tee slcb_init_process.log; exit ${PIPESTATUS[0]}"
    shell: "./slcb init -l debug -i inifile --namespace {{ slc_ns }} -u none 2>&1 | tee slcb_init_process.log; exit ${PIPESTATUS[0]}"
    environment:
      "{{ installer_env }}"
    args:
      chdir: "{{ installer_workspace }}"
      executable: /bin/bash
    ignore_errors: yes
    register: slcb_init_result
    until: slcb_init_result.rc == 0
    retries: 3
    delay: 60
    tags:
      - install
      - update

  - name: dump slcb.log
    shell: "cat {{ installer_workspace }}/slcb.log"
    environment:
      "{{ installer_env }}"
    args:
      chdir: "{{ installer_workspace }}"
      executable: /bin/bash
    tags:
      - install
      - update

  - name: Fail if slcb init failed
    assert: { that: "slcb_init_result.rc == 0 and slcb_init_result.changed == true" }
    tags:
      - install
      - update

  - name: slcb mirror
    shell: "./slcb copy -l debug -i inifile {{ docker_repository_flag }} {{ product_bridge_flag }} -u none 2>&1 | tee slcb_copy_process.log; exit ${PIPESTATUS[0]}"
    environment:
      "{{ installer_env }}"
    args:
      chdir: "{{ installer_workspace }}"
      executable: /bin/bash
    register: slcb_copy_result
    until: slcb_copy_result.rc == 0
    retries: 3
    delay: 60
    tags:
      - install
      - update

  - name: set_fact slcb_init = false
    set_fact:
      slcb_init: "false"
    tags:
      - install
      - update
  - name: generate inifile for slcb execute
    include: generate-inifile.yml
    tags:
      - install
      - update

  - name: install the DI via slcb execute
    shell: "./slcb execute -l debug -x -i inifile --namespace {{ slc_ns }} {{ docker_repository_flag }} --streamBridgeLog {{ product_bridge_flag }} -u none 2>&1 | tee slcb_execute_process.log; exit ${PIPESTATUS[0]}"
    environment:
      "{{ installer_env }}"
    args:
      chdir: "{{ installer_workspace }}"
      executable: /bin/bash
    ignore_errors: yes
    register: slcb_exec_result
    tags:
      - install
      - update
    #no_log: true

  - name: disable cron
    cron:
      name: "refresh acr token"
      state: "absent"
    tags:
      - install
      - update

  - block:
    - name: Create pods logs directory
      file: path="{{ installer_workspace }}/logs/podlogs" state=directory
    - name: Collect current logs
      shell: "python {{role_path}}/files/log_collector.py {{ installer_workspace }}/logs/podlogs --namespace {{ vora_kube_namespace }}"
      environment:
        "{{ installer_env }}"
    ignore_errors: true
    tags:
      - install
      - update
  - block:
    - name: Create pods describe logs directory
      file:
        path: "{{ installer_workspace }}/logs/pod_des_logs"
        state: directory
    - name: save all pod describe log
      shell: "python {{role_path}}/../vora-kubernetes-install/files/generate_pods_describe_log.py {{ vora_kube_namespace }} {{ installer_workspace }}/logs/pod_des_logs"
      environment:
          "{{ installer_env }}"
    ignore_errors: true
    tags:
      - install
      - update

  - name: copy slcb log files to playbook folder
    shell: "cp {{ installer_workspace }}/slcb*.log ./"
    args:
      executable: /bin/bash
    ignore_errors: true
    tags:
      - install
      - update

  - name: archive the slcb logs folder
    archive:
      path: "{{ installer_workspace }}/slcb.log"
      dest: "{{ installer_workspace }}/{{ slcb_log }}"
      format: zip
    ignore_errors: yes
    tags:
      - install
      - update

  - name: copy slcb log zip to playbook folder
    fetch:
      src: "{{ installer_workspace }}/{{ slcb_log }}"
      dest: "{{ slcb_log }}"
      flat: yes
    ignore_errors: yes
    tags:
      - install
      - update
  when: slcb_copy_workaround_result.rc == 0

- name: archive the logs folder
  archive:
    path: "{{ installer_workspace }}/logs"
    dest: "{{ installer_workspace }}/{{ archive_logs }}"
    format: zip
  ignore_errors: true
  tags:
    - install
    - update

- name: copy logs to playbook folder
  fetch:
    src: "{{ installer_workspace }}/{{ archive_logs }}"
    dest: "{{ archive_logs }}"
    flat: yes
  ignore_errors: true
  tags:
    - install
    - update

- name: Fail if slcb execute failed
  assert: { that: "slcb_exec_result.rc == 0 and slcb_exec_result.changed == true" }
  tags:
    - install
    - update

# install with enabled backup
- name: Set backup path prefix
  set_fact:
    di_backup_path_prefix: "{{ aks_cluster_name }}"
  when: enable_backup is defined and enable_backup == "true"
  tags:
    - install