---

- block:
  - name: login vsystem
    shell: ./vctl login {{vsystem_entry}} default {{vora_username}} --password {{vora_password}} --insecure
    args:
      executable: /bin/bash
      chdir: "{{ installer_path }}/tools"
    register: create_vflow_secret_login_result
    retries: 20
    delay: 15
    until: create_vflow_secret_login_result.rc == 0
  - name: create vflow-registry secret
    shell: './vctl secret create vflow-registry "username: \"$(printf {{acr_username.stdout}})\" ${IFS}password: \"$(printf {{acr_password.stdout}})\""'
    args:
      executable: /bin/bash
      chdir: "{{ installer_path }}/tools"
    register: create_vflow_secret_result
    retries: 20
    delay: 15
    until: create_vflow_secret_result.rc == 0
  - name: create vflow-registry secret
    shell: './vctl parameter set vflow.registrySecret vflow-registry'
    args:
      executable: /bin/bash
      chdir: "{{ installer_path }}/tools"
    register: set_vflow_secret_result
    retries: 20
    delay: 15
    until: set_vflow_secret_result.rc == 0
  when: installer_path is defined and installer_path != ""
  tags:
    - install
    - update

- block:
  - name: login vsystem
    shell: vctl login {{vsystem_entry}} default {{vora_username}} --password {{vora_password}} --insecure
    args:
      executable: /bin/bash
    register: create_vflow_secret_login_result
    retries: 20
    delay: 15
    until: create_vflow_secret_login_result.rc == 0
  - name: create vflow-registry secret
    shell: 'vctl secret create vflow-registry "username: \"$(printf {{acr_username.stdout}})\" ${IFS}password: \"$(printf {{acr_password.stdout}})\""'
    args:
      executable: /bin/bash
    register: create_vflow_secret_result
    retries: 20
    delay: 15
    until: create_vflow_secret_result.rc == 0
  - name: create vflow-registry secret
    shell: 'vctl parameter set vflow.registrySecret vflow-registry'
    args:
      executable: /bin/bash
    register: set_vflow_secret_result
    retries: 20
    delay: 15
    until: set_vflow_secret_result.rc == 0
  when: installer_path is undefined or installer_path == ""
  tags:
    - install
    - update
