- name: set user tenant user random password for bdh installation
  set_fact:
    vora_password: "bDh{{ lookup('password', '/dev/null length=2 chars=digits') }}@{{ lookup('password', '/dev/null length=5 chars=ascii_letters') }}"
  when: vora_password is not defined
  tags:
    - install
    - update

- name: set system tenant user random password for bdh installation
  set_fact:
    vora_system_tenant_password: "bDh{{ lookup('password', '/dev/null length=2 chars=digits') }}@{{ lookup('password', '/dev/null length=5 chars=ascii_letters') }}"
  when: vora_system_tenant_password is not defined
  tags:
    - install
    - update


