---
- set_fact:
    install_flag: "--update"
  tags:
    - update

- set_fact:
    install_flag: ""
  tags:
    - install

- include: common-install-parameters.yml

- name: set KUBECONFIG
  set_fact:
    installer_env:
      KUBECONFIG: "{{ eks_k8s_cluster_kubeconfig }}"
  tags:
    - install
    - update

- name: set eks install docker registry
  set_fact:
    eks_docker_install_registry: "{{ eks_docker_registry }}"
  when: eks_docker_registry_suffix is undefined or eks_docker_registry_suffix == ""
  tags:
    - install
    - update

- name: set eks install docker registry with suffix
  set_fact:
    eks_docker_install_registry: "{{ eks_docker_registry }}/{{ eks_docker_registry_suffix }}"
  when: eks_docker_registry_suffix is defined and eks_docker_registry_suffix != ""
  tags:
    - install
    - update

- name: set default eks vflow docker registry
  set_fact:
    eks_vflow_install_registry: ""
  when: eks_vflow_docker_registry_suffix is undefined or eks_vflow_docker_registry_suffix == ""
  tags:
    - install
    - update

- name: set eks vflow docker registry
  set_fact:
    eks_vflow_install_registry: "{{ eks_docker_registry }}/{{ eks_vflow_docker_registry_suffix }}"
  when: eks_vflow_docker_registry_suffix is defined and eks_vflow_docker_registry_suffix != ""
  tags:
    - install
    - update

#- include_role:
#    name: vora-update-certs
#  tags:
#    - update

- name: Starting vora installation process via slplugin
  include: eks-install-vora-slplugin.yml
  when: install_vora_via_slplugin == "true"

- name: Starting vora installation process via slcb
  include: eks-install-vora-slcb.yml
  when: install_via_slcb == "true"

- name: Starting vora installation process through install.sh
  include: eks-install-vora-installer.yml
  when: install_vora_via_slplugin == "false" and install_via_slcb == "false"

- fetch:
    src: "{{installer_workspace}}/install_process.log"
    dest: "{{ vora_installation_log }}"
    flat: yes
    fail_on_missing: no
  tags:
    - install
    - update
