---
- set_fact:
    aws_region: "{{kops_aws_region}}"
  when: kops_aws_region is defined

- set_fact:
    aws_region: "{{gardener_aws_region}}"
  when: gardener_aws_region is defined

- name: set aws configuration
  shell: "{{role_path}}/files/aws-set-config.sh {{ aws_access_key }} {{ aws_secret_key }} {{ aws_region }}"

- debug:
    msg: "cluster folder in bucket: {{s3_bucket_name}}/{{folder_name}}"

- name: delete the s3 bucket folder
  shell: "{{ role_path }}/files/delete-bucket-folder.sh {{ folder_name }} {{ s3_bucket_name }}"
