vault_credentials_file: "/vault_credentials.json"
vault_security_info: "{{ lookup('file', vault_credentials_file) | from_json }}"
vault_cicd_jfrog_user_name: "{{ vault_security_info.user }}"
vault_cicd_jfrog_api_key: "{{ vault_security_info.api_key }}"