---
# Stops (i.e. suspends) the monsoon cluster on VM level.
# The cluster can be started later with the start-monsoon-cluster script.

# Be aware: this required requires Ansbile >= 2.2.
# Ansible 2.1 has a bug related to starting/stopping EC2 instances.


- name: Stop Monsoon cluster
  hosts: workstation
  tasks:
    - assert: { that: ansible_version.major > 2 or
                 (ansible_version.major == 2 and ansible_version.minor >= 2 ) }
    - name: Stop instances of Monsoon cluster
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        ec2_url: "{{ ec2_endpoint_url }}"
        validate_certs: no
        source_dest_check: false
        state: stopped
        instance_ids: "{{ hostvars[item].inventory_hostname_short }}"
      with_items: "{{ groups['nodes'] }}"
